### ISSUE TITLE
Footer's copyright cannot contain links anymore

### ISSUE THREAD

**Issue by ottlinger** [zjedi/hugo-scroll#120]
Before the latest version updates I used footer's copyright to include other links and my config.toml looked like that:

```
[params]
    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© 1850-2023 Author / [Help](/help) &mdash; [Login](/login)"

```
That rendered properly.

Now the page does not render any markdown anymore, thus I'm unable to use this mechanism to add footer links such as legal stuff.

Is there a workaround (without patching my partial file in my themes directory)

Thanks

**Comment by zjedi** [comment]
The foter is now `safeHTML`, so that you can use classic HTML formatting and also `<a href="">`. Unfortunately it seems markdownify and safeHTML are exclusive features. Will HTML link work for you?

**Comment by ottlinger** [comment]
I tried removing the safeHTML in my themes subdir without any effects. Will try plain HTML instead.

**Comment by zjedi** [comment]
you can try replaceing safeHTML with markdownify locally

**Comment by ottlinger** [comment]
Ah, now I see your point: markdownify disables the HTML link and vice versa.
Maybe it's the easiest to just update the documentation in 
https://github.com/zjedi/hugo-scroll/blob/master/exampleSite/config.toml#L41

Thanks for the updates, I still struggle to get my old page working again, but do really enjoy the newly added features and customizability.

**Comment by zjedi** [comment]
Right, I'll review the docs sometime soon. We had a lot of changes recently so it needs to settle down a bit. More features are coming :)

**Comment by ottlinger** [comment]
Thanks for the merge.
