### ISSUE TITLE
Provide option to show GitInfo in footer

### ISSUE THREAD

**Issue by ottlinger** [zjedi/hugo-scroll#126]
Following 
* https://www.brycewray.com/posts/2022/06/get-good-git-info-hugo/
* https://stackoverflow.com/questions/57141806/how-can-i-get-gitinfo-in-hugo#57152994
it should be rather easy to integrate a gitInfo into the theme.

Personally I'd prefer a git hash that is shown if 
`--enableGitInfo` is used or config.toml contains 
`enableGitInfo=true`
similar to the link shown depending on the configuration option `hidedesignbyline`.

Any thoughts on that? (Before I start with a PR) :)

Thanks

**Comment by zjedi** [comment]
Sounds like a feature relevant mostly to tech savvy people, I think it should be opt-in. `enableGitInfo=true` with default value false sounds good to me. I don't have strong views on this, do it the way that fits you best :)

**Comment by ottlinger** [comment]
Thanks.
