### ISSUE TITLE
Changelog and semantic versioning to keep track of changes

### ISSUE THREAD

**Issue by ottlinger** [zjedi/hugo-scroll#128]
WDYT, would it make sense to change from a list in contributing.md to use
* https://keepachangelog.com/en/1.0.0/ and
* https://semver.org/spec/v2.0.0.html
to release changes?

I'm not sure about release strategies in the hugo-themes sphere, but package.json seems to have a fixed version .....

**Comment by zjedi** [comment]
Yup, it would make sense, especially now that the project is getting more alive. It's on my todo list. I think there was a fixed version from the beginning.
