### ISSUE TITLE
Trying to get content to display in columns

### ISSUE THREAD

**Issue by dabanhfreak** [zjedi/hugo-scroll#144]
I've been trying to have one of the content blocks display text in 2-3 columns, but for the life of me I can't figure it out.
I'm a novice css/HTML user so some help would be appreciated.

I've been trying to implement the solution listed [here](http://oostens.me/posts/hugo-column-shortcode/) but can't the result I'm looking for.

**Comment by dabanhfreak** [comment]
i just simply downloaded the sample html and put it in the shortcodes folder, the same way I did it for email sub boxes and ecommerce.
Truth be told I don't really know what I'm doing here.

**Comment by zjedi** [comment]
>is that a security risk?
That's a question only you can answer. The basic guideline I'd suggest to consider: do you have any secrets in the repo?

I might try theose shortcodes someday, but it will take some time (weeks-months) for me to do it.

Layout-changing shortcodes can be problematic and the worst case here is it's not easily supported without some theme adaptations.

**Comment by juanMarinero** [comment]
@dabanhfreak 

### Hugo Shortcodes

Read [my blog](https://juanmarinero.github.io/blogs/hugo_shortcodes/) to understand built-in shortcodes.

### Hugo Scroll Shortcodes

Hugo Scroll theme defines few more, quick explained [here](https://juanmarinero.github.io/blogs/hugo_shortcodes/#hugo-scroll). Thus, in this repo just ask about those shortcodes please.

### Study Hugo
- The [docs](https://gohugo.io/documentation/)
- [External learning resources](https://gohugo.io/getting-started/external-learning-resources/)
- Questions in [Discourse](https://discourse.gohugo.io/)
- Self promotion: https://juanmarinero.github.io/blogs/

### CSS and HTML

> I'm a novice css/HTML

A basic knowledge in both is needed to customize your Hugo project.

Copy the CSS content (SCSS in [Oostens post](https://oostens.me/posts/hugo-column-shortcode/)) into your `layouts/partials/custom_head.html` (inside the `<style>` tags).
Read [my blog](https://juanmarinero.github.io/blogs/create_hugo_website/#css) for details.

### Hugo Column shortcode by Nelis Oostens modified

`layouts/shortcodes/columns.html` shortcode template:

```go
<div class="md-columns">
  {{ range split .Inner "<--->" }}
    <div class="markdown-inner">
      {{ . | $.Page.RenderString }}
    </div>
  {{ end }}
</div>
```

Note. Removed `htmlUnescape` and `safeHTML`. Added `$.Page.RenderString`

Structure
- **Outer container**: `<div class="md-columns">` - wraps all columns
- **Inner columns**: Each section separated by `<--->` becomes a column wrapped in `<div class="markdown-inner">`

How it works

0. Wrap all in `<div class="md-columns">` and `</div>`
1. **Splits content**: Uses `split .Inner "<--->"` to divide the content into sections wherever `<--->` appears. Use `range` to loop them.
2. **Creates columns**: For each section, it generates next. The dot (`.`) holds the loop value described in previous step, i.e. the `[content]` of current *split*.
   ```html
   <div class="markdown-inner">
     [content]
   </div>
   ```
3. **~~Safety handling~~Render HTML**: Uses `$.Page.RenderString` to properly render HTML content. For example the `*cursive words*` in the *usage example* below it's rendered to `<em>cursive words</em>`.
4. Loop steps 1 to 3 as many times as the `range split .Inner "<--->"` dictates for your shortcode content.

Usage example.
Call the *column* shortcode with:

```markdown
{{< columns >}}
First column content
<--->
Second column content with *cursive words*
<--->
Third column content
{{< /columns >}}
```

Result
```html
<div class="md-columns">
  <div class="markdown-inner">First column content</div>
  <div class="markdown-inner">Second column content with <em>cursive words</em></div>
  <div class="markdown-inner">Third column content</div>
</div>
```

Screenshot

<img width="675" height="58" alt="Image" src="https://github.com/user-attachments/assets/8c196e3c-c0b2-47c5-aecb-424750a3d608" />
