### ISSUE TITLE
git push to netlify uses exampleSite theme colours

### ISSUE THREAD

**Issue by dabanhfreak** [zjedi/hugo-scroll#146]
When I do 'hugo', and manually deploy to netlify, my website works fine.
However, when I do a git push to github, and then let netlify deploy from the repo, it uses the exampleSite colours,
ie the cover headline is in green, and the colours are white/light red.
No idea why it is doing this, did I miss something?

**Comment by zjedi** [comment]
Not sure, sounds like some kind of misconfiguration, linking wrong resources maybe? How is your deployment configured?

**Comment by zjedi** [comment]
@dabanhfreak did you manage to configure it?
