### ISSUE TITLE
Link de-activation glitch on Safari iOS

### ISSUE THREAD

**Issue by e-basteln** [zjedi/hugo-scroll#149]
I found an issue with the main menu when using Safari (iOS): A link which was activated by tapping it will not be de-activated by scrolling to another section of the page. Scrolling will properly activate and deactivate new links, matching the current page view, but the previously tapped link always remains active in addition. It can only be de-activated by *tapping* on another link. 

Link activation and de-activation with mixed clicking/scrolling works fine under Chrome, Edge and Firefox on the desktop (Windows). What -- presumably in index.js -- could be causing the glitch under iOS?

**Comment by zjedi** [comment]
Hi, unfortunately I don't have access to Safari browser to test it out. Can you somehow debug it in your browser, maybe check js console to see if there are any errors?

**Comment by e-basteln** [comment]
I only have access to the mobile version of Safari on iOS myself, and that one needs a connection to a desktop Mac to do debugging, I understand. I will try to find a Mac to see whether desktop Safari behaves the same, and/or get debug messages from the iOS version.

**Comment by zjedi** [comment]
@e-basteln what is the problematic browser version?

**Comment by e-basteln** [comment]
@zjedi, I have tested this under iOS 16.6 (most recent version for current iPhones, I believe) and 15.7.8 (Apple's actively supported version for older iPhones). I guess that means Safari 16 and 15, respectively, since they don't get separate version numbers. Both show the glitch I described.

**Comment by zjedi** [comment]
I have no access to Mac, not goint to fix this on my own, mybe someone else can cave a look.
