### ISSUE TITLE
Creating a Page on Github Using Hugo Themes

### ISSUE THREAD

**Issue by florverde** [zjedi/hugo-scroll#150]
I'm trying to use the Hugo Pages theme with github: https://github.com/lq-2022/hugo-scroll to create a personal page. I generally do it this way:

1 - I create a new repository;

2 - Use username.github.io as the repository name;

3 - I download the theme zip file and, after extracting the files, I upload them via git and Rstudio to the github repository.

4 - Finally, I change the config.toml files in Rstudio to leave the page with my information.

However, when doing this with this theme I can only see the following page: https://florverde.github.io/ which is, precisely, the README.MD of the theme. In the README.MD file itself, it is suggested to copy the files from the exampleSite folder and replace the files from the source folder with them, however, when doing this, I receive the 404 error message. I would like a suggestion on how to use this theme! I found pages with the same installed, as shown below, and I've already tried to clone them, but I get the same error:

1 - https://lq-2022.github.io/

2 - https://ksmony.github.io

3 - https://TD-Hackathon-2022.github.io

**Comment by zjedi** [comment]
@florverde I can see the pages you link are working, I supposed you got it working by yourself in the end :) I like the timeline feature you used in 3), care to share source code?
