### ISSUE TITLE
List icon configurable

### ISSUE THREAD

**Issue by spi43984** [zjedi/hugo-scroll#151]
The asterisk icon fa-asterisk in unnumbered lists is quite too big in my web text.

I changed it by editing hugo-scroll/tree/master/assets/js/index.js - but is there a nicer way to achieve this like defining a variable in layouts/partials or something?

Cheers,
spi

**Comment by zjedi** [comment]
Good idea, @spi43984, it would be nice feature.

**Comment by zjedi** [comment]
@spi43984 look it could work. I've added a few comments/questions. Thanks for contributing.

**Comment by zjedi** [comment]
Looks working.
