### ISSUE TITLE
Smooth transition sections not working in Edge

### ISSUE THREAD

**Issue by jbwaagmeester** [zjedi/hugo-scroll#161]
I've used hugo-scroll for two projects. The older version has the smooth transition between the sections and the newer one (like the current demo of the website) doesn't. Would it be possible to bring this back? Especially when using the menu I think this is a better experience. 

Some details (obtained from the theme.toml file):

- [Older website](https://tabula.libripendis.eu/) uses version 0.41.0
- [Newer website](https://daemon.libripendis.eu/) uses version 0.111.2

**Comment by zjedi** [comment]
can you provide more context? Browser, version. The smooth scroll works for me, it's just a bit faster now. Hae you tried clearing cache?

**Comment by jbwaagmeester** [comment]
I use Edge (118.0.2088.61) and Vivaldi (6.2.3105.58) on W11 (22H2). 

However, even after clearing cache I run into the same issue where the old one seems to be working and the newer one doesn't. I can even try the same thing on virtual machines using [Browserling](https://www.browserling.com/) for Firefox, Chrome and Opera and I still run into the same issue. The newer version of hugo-scroll will not transition smoothly between the sections for me.

**Comment by zjedi** [comment]
Can you describe what you click on to replicate the problem? Maybe I'm clicking something else.

**Comment by jbwaagmeester** [comment]
I load the page, click on the arrow to go to the first section and then on the menu. See the gif I made below: 

Old version: https://pasteboard.co/KeI4Xk3w1eKF.gif
New version: https://pasteboard.co/AD6xipN03oJR.gif

I have to say that on my mobile phone (Pixel 6a, Android 14 - oct. 23 update) using Edge (117.0.2045.65) and Chrome (118.0.5993.80) it does work for both websites.

**Comment by zjedi** [comment]
@jbwaagmeester For me the new website does scroll smootly, are you still experiencing the issue?

I can feel that Edge does the transition somewhat faster, compared to other browsers, that might be something to look into.

**Comment by jbwaagmeester** [comment]
Not experiencing this issue any longer. Some update to Edge must've resolved the issue.
