### ISSUE TITLE
"Return to top" link in menu does not work

### ISSUE THREAD

**Issue by pvarela** [zjedi/hugo-scroll#162]
The "Return to top" link in the menu does not work.

I think it can be fixed by changing the href to "./#site-head" in line 57 of layouts/index.html which currently says:

            <a class='fn-item' item_index='{{ 0 }}' href='/#site-head'>{{ $fnav_title | safeHTML }}</a>

**Comment by zjedi** [comment]
@pvarela Thanks, confirmed problem. I'll have a look into it.

**Comment by zjedi** [comment]
> it links to e.g. github.site/#site-head instead of github.site/mysite/#site-head

**Comment by zjedi** [comment]
@pvarela thanks for suggestion, it seems to have fixed it.
