### ISSUE TITLE
Contact icons are not centered in the footer

### ISSUE THREAD

**Issue by filippofontana** [zjedi/hugo-scroll#171]
The contact icons in the footer are declared as a list of links and, due to `<li>` css rules, they have a margin left of 20px which makes them not aligned with the rest of the footer's content. This is more visible when you have, for instance, three contact icons.

Example:

![list](https://github.com/zjedi/hugo-scroll/assets/55811966/fe703371-e514-4771-9d65-cc8588d3a7c9)

I have prepared a new commit with the contact icons displayed without the `<li>` tag and using flex for displaying and aligning stuff (with some padding to emulate the previous style). If this sounds ok, I can submit a pull request.

Example of the updated design:

![flex](https://github.com/zjedi/hugo-scroll/assets/55811966/8482b0cc-9b3a-4794-aa42-a337828e4265)

Let me know what you think!

**UPDATE**: _of course I can replicate exactly the padding between the icons and the other stuff under them and also between the icons themselves._

**Comment by zjedi** [comment]
looks good!

**Comment by nai888** [comment]
@zjedi Nope, feel free to change it!

**Comment by filippofontana** [comment]
Ok, thanks for the feedback guys! I'll send a PR soon.

**Comment by filippofontana** [comment]
Solved with #172.
