### ISSUE TITLE
BUG: `tel:` link is broken with the new dynamic contacts system

### ISSUE THREAD

**Issue by filippofontana** [zjedi/hugo-scroll#173]
Basically, when you insert **urls** dynamically with the Hugo template system, only `http:`, `https:` and `mailto:` are considered safe (see this [page](https://gohugo.io/functions/safe/url/) in the documentation for better context).

The solution is just to give the `.url` parameter to the `safeURL` function.

The issue is introduced in #170.

**Comment by zjedi** [comment]
Im ok with safeUrl, user is responsible for value parameters and they are defined in config file, no risk of injection from outside.

**Comment by filippofontana** [comment]
I'm going to submit a pull request then.
