### ISSUE TITLE
Rename config.toml to hugo.toml in exampleSite

### ISSUE THREAD

**Issue by Daniel-The-Fox** [zjedi/hugo-scroll#191]
Hi there,

I'm new to Hugo and found your great Hugo template hugo-scroll which I'm planning to use for a company website within the next months, once the company is founded... ;)

While following the [Hugo QuickStart guide](https://gohugo.io/getting-started/quick-start/) in conjunction withe the [Readme of the Hugo Scroll template](https://themes.gohugo.io/themes/hugo-scroll/), I (as a new Hugo user) got confused for a minute when I copied the content of the exampleSite folder to the folder of my new website. I linked my new Hugo site to the Hugo Scroll template before copying over the contents from the example website.

What irritated me, was that the example website is using a `config.toml` as a config file for Hugo, while the (new) [default config file for Hugo is called `hugo.toml`](https://gohugo.io/getting-started/configuration/).

I think it would things easier for new users if you would rename config.toml to hugo.toml. 😄

**Comment by zjedi** [comment]
Hm, ok that must be something that changed over the years. If they are equivalent and compatible it sounds a good idea to adhere to the standard.
