### ISSUE TITLE
invalid type <icon> should be <i> for fork awesome

### ISSUE THREAD

**Issue by schellingerhout** [zjedi/hugo-scroll#195]
https://github.com/zjedi/hugo-scroll/blob/807c028d71512e31291683b204d7e35c2a704bbe/layouts/index.html#L67

Relatively harmless in real world, but causes a W3 validator tool error.

Simply replace `icon` with `i` and issue is resolved

this is in line with the shortcode

https://github.com/zjedi/hugo-scroll/blob/807c028d71512e31291683b204d7e35c2a704bbe/layouts/shortcodes/icon.html#L1

**Comment by zjedi** [comment]
Sounds truly harmless, would you care to open a pull request for this?

**Comment by schellingerhout** [comment]
Sure! I'll do that tonight
