### ISSUE TITLE
WARN  deprecated: resources.ToCSS was deprecated in Hugo v0.128.0 and will be removed in a future release. Use css.Sass instead.

### ISSUE THREAD

**Issue by egelmex** [zjedi/hugo-scroll#207]
> WARN  deprecated: resources.ToCSS was deprecated in Hugo v0.128.0 and will be removed in a future release. Use css.Sass instead.

https://github.com/zjedi/hugo-scroll/blob/be2014bf8c270ab411d76b509978f7865b91e951/layouts/partials/head.html#L28

**Comment by foxyseta** [comment]
I think this is being taken care of by #207.
