### ISSUE TITLE
CSS easy to customize

### ISSUE THREAD

**Issue by appieschot** [zjedi/hugo-scroll#4]
First off compliments on the template! I love it! However I would love to apply my own branding (colours) so it would be awesome to support CSS overrides. I am more than happy to submit a PR that implements a CSS override option if you are open to that! 

I could imagine using the head.html to add an `override.css` in case the parameter is specified. We could even use the asset bundling option Hugo provides to combine CSS files. Feel free to assign to me and let me know if you want me to pick it up.

**Comment by janraasch** [comment]
Hi @appieschot, thank you for getting in touch **&** thank you for the kind words 😊.

> However, I would love to apply my branding (colors), so it would be awesome to support CSS overrides.

This question comes up quite a lot, see https://github.com/janraasch/hugo-scroll/issues/2#issuecomment-675389713 & https://github.com/janraasch/hugo-scroll/issues/1#issuecomment-671774363. I have not documented the process on `README.md`, but will do so now 😇.

Here's what you can do to add your own CSS:

* Add a `custom_head.html` to your `layouts/partials`-directory. If you started from the `exampleSite` on this repo, you should already have such a file.

* In there you can add a <style>-tag to overwrite the colors **or**

* you can add a `<link>`-tag referencing your own `override.css` (in case you prefer to have a separate `.css`-file).

I hope that helps. Let me know if this is what you had in mind.

Kind regards 👋 ,
Jan

PS:

I updated the README with the instructions mentioned above. Check out https://github.com/janraasch/hugo-scroll#adding-your-branding--colors--css.

**Comment by appieschot** [comment]
Thanks for the clarification! Definitely got it working, however I only wanted to add CSS so I could apply [asset bundling](https://gohugo.io/hugo-pipes/bundling/) for optimal speed.

**Comment by janraasch** [comment]
> Thanks for the clarification!

Sure 👍.

> [...] optimal speed [...]

That sounds like something one should have 😛 😇 😊.

In that case, you would (*for the time being* 😊) have to overwrite [layouts/partials/head.html](https://github.com/janraasch/hugo-scroll/blob/master/layouts/partials/head.html) with a local copy including your asset bundling solution.

That should fix the issue for you then 😊.

-----------

If you have some time, I would also like to see how we could integrate this into the theme. 

In a dream world scenario, I would love to have the `.css` parsed by [Hugo Pipes](https://gohugo.io/hugo-pipes/scss-sass/) with a `variables.css` which has variables for the different colors. So it is basically plug-and-play to add custom branding. I should open an `idea`-issue for this.

Anyway, if your up for it, feel free to open a pr (for asset bundling and/or the dream world scenario 😉). Then we can carry on the conversation with some *real* source code to get a better feel for this feature.

**Comment by appieschot** [comment]
Sure, just created a [fork](https://github.com/appieschot/hugo-scroll/tree/feature/hugo-pipes-support) where I added a _customvars.scss. Basics works, so I will go through the CSS file and properly construct the theme. It does require the extended version of Hugo but so far things look good ;-). Will use the weekend to update and create a PR 😎

**Comment by zjedi** [comment]
#98 goes towards this goal

**Comment by zjedi** [comment]
@appieschot We finally implemented CSS variables for overriding. It's the first version that may still evolve a bit throughout 2.0 release planned for this year
