### ISSUE TITLE
Request: use name instead of title for navigation

### ISSUE THREAD

**Issue by metbril** [zjedi/hugo-scroll#41]
Currently, the "title" is used to display in the navigation menu. 

I want to use a larger page/section title, but would like to use a shorter text for the menu. For example, I have a "now" page which I'd like to title "What I'm doing now", but I'd like the navigation (and the anchor) to show "Now" and the anchor link to be `#now`.

This is similar to how standard Hugo menus work.

https://gohugo.io/content-management/menus/

sample markdown header:

```markdown
---
title: What I'm doing now
name: Now
weight: 20
header_menu: true
---
```

**Comment by metbril** [comment]
Keep

**Comment by zjedi** [comment]
Now supported, see exampleSite
