### ISSUE TITLE
Add header video background

### ISSUE THREAD

**Issue by thomasjungblut** [zjedi/hugo-scroll#46]
Hey Jan,

I really love your template and use it quite often to create quick websites, thanks a lot.

Yesterday I experimented a bit with videos in the header (instead of the image or plain color background) and added support for this in this commit:

https://github.com/thomasjungblut/hugo-scroll/commit/126fbdeea838f245088eb0bc4f6c670480593786

Would you be interested to include this in here? Happy to contribute this back.

**Comment by janraasch** [comment]
Hi @thomasjungblut, thank you for getting in touch. It is nice to meet you 🤝 😁.

I bet a lot of people would appreciate this feature 📹 🎥 👍.

See you on the pr then 👋 🙂.

**Comment by janraasch** [comment]
PS: Oh and by the by - I am always interested how this theme is used in the wild - can you share a link to the site with the video header? Thanks!

**Comment by zjedi** [comment]
Hi @thomasjungblut, as a new maintainer of the template, I'm reopening the issue. I'd like to have this feature available for everyone, will you be able to open a PR? It's been a while, maybe your solution underwent some changes in the meantime?

**Comment by thomasjungblut** [comment]
@zjedi congrats! I haven't done any changes to the template, I think you can just cherry-pick the commit from https://github.com/thomasjungblut/hugo-scroll/commit/126fbdeea838f245088eb0bc4f6c670480593786 and see if it applies fine.

**Comment by zjedi** [comment]
Transplnated.
