### ISSUE TITLE
Add instagram feed to posts

### ISSUE THREAD

**Issue by gjvengelen** [zjedi/hugo-scroll#52]
Hi,

I really love your theme I'm making a website for my wife's store and wanted to add an Instagram feed.
I've done a small adjustment to the index.html to make it possible to add an Instagram feed to a post.
```html
<main class="content" role="main">

    <div class='fixed-nav'>
    </div>
    {{ range $index_val, $elem_val := $sections }}
    <div class='post-holder'>
        <article id='{{ anchorize .Title }}'
            class='post {{ if eq $index_val 0 }}first{{ end }} {{ if eq (add $index_val 1) (len $sections) }}last{{ end }}'>
            <header class="post-header">
                <h2 class="post-title">{{ .Title }}</h2>
            </header>
            <section class="post-content">
                {{ .Content }}
                {{ if isset .Params "insta" }}
                {{ partial "instafeed.html" . }}
                {{ end }}
            </section>
        </article>
        <div class='post-after'></div>
    </div>
    {{ end }}
    <div class='post-holder'>

    </div>
</main>
```
And added an instafeed.html to render the instafeed, which uses https://profilepageimages.usecue.com to fetch your Instagram images. You can go upto 25 images and it's configurable via the font data in the .md files. Which would look something like:
---
title: 'Kleding'
weight: 2
header_menu: true
insta: true
instautl: https://profilepageimages.usecue.com/{username}
instaamount: 3
---
![image](https://user-images.githubusercontent.com/79509387/157001944-8c24dc46-f1cd-4f4f-a2e6-8c14ab22eac4.png)

Would you be interested in adding this as a default feature, I could make an mr if so.
A link to a preview website: https://gjvanengelen.gitlab.io/lemon-hill/

BR Gerard

**Comment by zjedi** [comment]
Hi, as a new maintainer I reopen the issue, would you be able to open a PR with this feature?

**Comment by gjvengelen** [comment]
Yes, but probably will have time by the end of the month.
