### ISSUE TITLE
Problem with very long desktop screen

### ISSUE THREAD

**Issue by neclepsio** [zjedi/hugo-scroll#58]
Using the default demo and 1200x1600 screen, the second of four elements is still active when reaching the bottom. Since when reaching the bottom of the page the active class is cleared for the third element, both second and fourth are active.

I suggest replacing line 86 of index.js:

    $(".fn-item[item_index='" + (l - 1) + "']").removeClass("active")

With:

    $(".fn-item").removeClass("active")

**Comment by mathijsqdrop** [comment]
I ran into the same problem and your fix works for me 👍

**Comment by zjedi** [comment]
Fixed by #135
