### ISSUE TITLE
Sticky Header Menu not available on mobile screens

### ISSUE THREAD

**Issue by equusit** [zjedi/hugo-scroll#90]
The top sticky menu for narrow scenes doesn't seem to appear on screen resolutions of less than or equal to 500px wide. If the resolution starts above this, the page is scrolled to trigger the menu and then the screen width reduced below 500px the menu stays in place and works fine. Is there a way around this?

**Comment by susnux** [comment]
Would be fixed by https://github.com/janraasch/hugo-scroll/pull/93

If you like, you can try it by using temporary my fork (until this is resolved :) ): https://github.com/susnux/hugo-scroll

**Comment by zjedi** [comment]
I had the same problem and eventually I put the menu on top of the page as a row. The side menu is just not feasible on smaller screens.

**Comment by zjedi** [comment]
top menu implemented
